spring:
  application:
    name: backend-springboot

  datasource:
    url: jdbc:mysql://localhost:3306/intelligent_recruitment_system?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # Thay đổi từ validate thành update để tự động tạo bảng 'applications' còn thiếu
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: tpn18092004@gmail.com
    password: gtzgsmjcdzanimek
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Cấu hình JWT và các dịch vụ khác
jwt:
  secret: "oUwfZl+T7r7+Jw5bB65zW98Mt3jzYtPClpZ3aINxqVQ="
  expiration: 86400000

cloudinary:
  cloud-name: dwd4b8lcx
  api-key: "271116451416351"
  api-secret: fbyd8zzUl4OSzBFxkf4_cr4jNTk

vnpay:
  tmn-code: 63NUWGNE
  hash-secret: C3NBM8MWADUJ1HDMU1KZ67YICMAD9BSJ
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/payments/vnpay/callback